dropout_rate: 0.3
label_smoothing_wt: 0.1
ment_loss: 'all'
normalize_loss: False
max_evals: 20
to_save_model: True
log_frequency: 500
patience: 5
eval_per_k_steps: null
num_training_steps: null
max_training_segments: 1
ment_loss_wt: null